"use strict";
globalThis.PrecisionPanel=class {
  constructor(root){
    this.root=root;this.data=null;this.running=false;this.paused=false;this.cancelled=false;
    this.names={baseline:"Baseline",more_atoms:"More atoms",more_shots:"More shots"};
    this.colors={ideal:"#16796e",finite:"#ba7b2c"};
    root.innerHTML=`<div class="panel-title"><div><p class="eyebrow">PRECISION BENCHMARK / REPEAT THE WHOLE SCAN</p><h2>Precise. But is it accurate?</h2></div><span class="tag">Fresh counts in every repetition</span></div>
    <p>Repeat the full phase readout, then compare the distribution of estimated phases with the uncertainty reported by each scan. More atoms and more shots can reduce random scatter; a biased pulse can still put a narrow distribution in the wrong place.</p>
    <div class="tm-actions"><button id="pb-calibrated">Check counting precision</button><button id="pb-biased">Precise but biased</button><button id="pb-dark">No identifiable phase</button></div>
    <div class="ep-controls"><label>Baseline atoms N<input id="pb-atoms" type="number" min="2" max="99" value="20"></label><label>More atoms N<input id="pb-more_atoms" type="number" min="3" max="100" value="80"></label><label>Baseline shots / setting<input id="pb-shots" type="number" min="16" max="4095" value="64"></label><label>More shots / setting<input id="pb-more_shots" type="number" min="17" max="4096" value="256"></label><label>Full-scan repetitions<input id="pb-repetitions" type="number" min="20" max="300" value="100"></label><label>Reference phase settings<input id="pb-points" type="number" min="8" max="32" value="12"></label><label>Initial phase / rad<input id="pb-phase" type="number" step="any" value="0.7"></label><label>Readout J / Hz<input id="pb-pulse_j_hz" type="number" min="0.5" max="20" step="any" value="10"></label><label>Bias δ / Hz<input id="pb-bias_hz" type="number" min="-20" max="20" step="any" value="0"></label><label>Pulse duration error / %<input id="pb-error" type="number" min="-50" max="50" step="any" value="0"></label><label>Seed<input id="pb-seed" type="number" min="0" max="4294967295" value="17"></label></div>
    <details><summary>Initial state and hold</summary><div class="ep-controls"><label>Initial state<select id="pb-initial"><option value="coherent">Coherent binomial</option><option value="gaussian">Prescribed number-narrow state</option><option value="fock">Fixed occupation</option></select></label><label>Initial left fraction<input id="pb-left_fraction" type="number" min="0" max="1" step="any" value="0.5"></label><label>Gaussian σ / atoms<input id="pb-sigma" type="number" min="0.25" max="20" step="any" value="1.5"></label><label>Hold / ms<input id="pb-hold_ms" type="number" min="0" max="1000" step="any" value="0"></label><label>Interaction U / Hz<input id="pb-interaction_hz" type="number" min="0" max="2" step="any" value="0"></label><label>Hold protocol<select id="pb-echo"><option value="false">Free isolated hold</option><option value="true">Ideal midpoint echo</option></select></label></div><p>All cases use the same initial-state recipe. Changing N can also change interaction dynamics; the simple precision guide is shown only for balanced coherent states with U=0. There is no technical preparation noise.</p></details>
    <p class="muted">One repetition is a complete scan in all three cases, with independent ideal and finite-pulse counts. The workload limit is 16 million count draws. Model probabilities are reused because the preparation is identical; count outcomes and phase fits are newly generated every time.</p>
    <div class="tm-actions"><button id="pb-run" class="primary">Run precision benchmark</button><button id="pb-pause" disabled>Pause benchmark</button><button id="pb-cancel" disabled>Cancel benchmark</button><button id="pb-json" disabled>Export precision JSON</button><button id="pb-csv" disabled>Export precision CSV</button></div>
    <p id="pb-status" role="status" aria-live="polite">Ready. Settings apply on Run; previous experiments remain intact.</p>
    <div id="pb-results" hidden><p id="pb-applied" class="muted"></p><p class="muted">Scroll tables sideways to see all measurements on smaller screens.</p><div class="ep-table"><table><thead><tr><th>Case</th><th>N</th><th>Shots / setting</th><th>Cloud preparations / scan / arm</th><th>Atom uses / scan / arm</th><th>Ideal scatter guide / rad</th></tr></thead><tbody id="pb-budgets"></tbody></table></div>
    <div id="pb-scaling" class="chart"></div><div class="fp-legend"><span style="color:#16796e">● Ideal: observed scatter</span><span style="color:#ba7b2c">● Finite: observed scatter</span><span>□ RMS reported SE · × ideal analytic guide</span></div>
    <div class="ep-table"><table><thead><tr><th>Case / arm</th><th>Resolved / attempted</th><th>Circular bias / rad</th><th>Circular scatter / rad</th><th>RMS reported SE / rad</th><th>Scatter / SE</th><th>Wrapped RMSE / rad</th><th>Within ±1 SE of truth</th><th>Noiseless pulse bias / rad</th></tr></thead><tbody id="pb-summary"></tbody></table></div>
    <p class="muted">All phase statistics condition on resolved scans; unresolved outcomes remain in the attempted count. At least two resolved scans are needed. Scatter measures precision around the estimated center; bias and RMSE refer to the incoming model phase. The ±1 SE fraction is an empirical check, not a confidence guarantee. SE excludes pulse bias.</p>
    <label>Inspect repeated phase estimates<select id="pb-case"><option value="baseline">Baseline</option><option value="more_atoms">More atoms</option><option value="more_shots">More shots</option></select></label>
    <div id="pb-histogram" class="chart"></div><p id="pb-hist-note"></p><p class="muted">Shared bins; bar heights are fractions of all completed scans. Unresolved phases do not enter the bars. Errors are wrapped to ±π around each case's true phase. The vertical zero line marks truth; dotted lines mark noiseless readout bias. The horizontal range adapts to the selected case.</p></div>
    <details><summary>Precision guide, statistics and limits</summary><p>This uses the phase gate and fixed-N Hamiltonian of Phase readout above: H/h = −J(a†L aR + a†R aL) + U(n−N/2)² − δ(n−N/2), with frequencies in Hz, time in ms and Σ|cₙ|²=1. The ideal π/2 operation is instantaneous; finite readout retains U and δ for (1+error)/(8J) seconds. Every arm starts from the same pre-readout state and every shot is a freshly prepared copy. No real-time renormalization is applied.</p><p>Each scan independently fits z=offset+a cos α+b sin α using counts alone. Phase=atan2(b,a); the v0.14 visibility gate masks weak fits. Circular bias uses the circular mean minus truth; circular scatter is sqrt(−2 log R), with R the mean unit-vector length. Wrapped RMSE includes bias and random error. RMS reported SE is sqrt(mean(SE²)). Missing model phase means bias and RMSE are unavailable. If almost all fits are unresolved, the few surviving estimates do not establish precision.</p><p>For balanced coherent states at U=0, the ideal full-period unweighted estimator has the large-shot prediction σφ≈sqrt[3/(2NKS)], with K reference phases and S shots per setting. This is specific to this estimator. It is not the optimal local standard quantum limit 1/sqrt(NKS), and no quantum advantage is claimed. Finite samples can differ from the guide; higher N can change interacting or number-narrow preparations.</p><p>Independent pseudo-random blocks are assigned in repetition, case, setting, arm order. Reusing deterministic states avoids repeating identical propagation, not fresh counting. Counts, fits, seeds and model states are saved for independent Python replay. Pause/cancel retains complete paired repetitions. Detector noise, loss, technical preparation variation and spatial excitations remain omitted.</p><p><a href="https://www.nature.com/articles/nature08919" target="_blank" rel="noopener">Gross et al., Nature (2010) ↗</a> motivates comparing phase sensitivity at controlled resources. Its interaction-generated quantum enhancement is not reproduced by this baseline benchmark.</p></details>`;
    this.$=id=>root.querySelector(`#pb-${id}`);
    this.baseFields=["atoms","phase","bias_hz","interaction_hz","left_fraction","sigma"];
    this.readoutFields=["shots","points","pulse_j_hz","hold_ms","seed"];
    this.fields=["more_atoms","more_shots","repetitions"];
    for(const name of ["calibrated","biased","dark"])this.$(name).onclick=()=>this.preset(name);
    this.$("run").onclick=()=>this.run();this.$("pause").onclick=()=>{this.paused=!this.paused;this.buttons();this.render();this.message(this.paused?"Paused between completed full-scan repetitions.":"Resuming benchmark…");};this.$("cancel").onclick=()=>{this.cancelled=true;this.paused=false;};
    this.$("case").onchange=()=>this.render();this.$("json").onclick=()=>this.download("json",JSON.stringify(this.data));
    this.$("csv").onclick=()=>{const d=this.data,rows=[["status","trial","case","arm","N","shots","settings","seed","initial","initial_phase_rad","left_fraction","sigma","hold_ms","echo","U_hz","bias_hz","readout_J_hz","duration_error","true_phase_rad","phase_rad","phase_se_rad","resolved","contrast","residual_rms_z"]];for(const r of d.records)for(const m of d.models)for(const a of Precision.arms){const f=r.cases[m.name][a].fit,p=m.plan,b=p.base;rows.push([d.status,r.index,m.name,a,b.atoms,p.shots,p.points,p.seed,b.initial,b.phase,b.left_fraction,b.sigma,p.hold_ms,p.echo,b.interaction_hz,b.bias_hz,p.pulse_j_hz,p.duration_error,m.source.phase??"",f.phase??"",f.phase_se??"",f.resolved,f.contrast,f.residual_rms]);}this.download("csv",rows.map(r=>r.join(",")).join("\n")+"\n");};
    new ResizeObserver(()=>this.render()).observe(this.$("scaling"));
  }
  message(t,error=false){this.$("status").textContent=t;this.$("status").classList.toggle("error",error);}
  preset(name){const p=Precision.defaults;for(const k of this.baseFields)this.$(k).value=p.readout.base[k];for(const k of this.readoutFields)if(k!=="seed")this.$(k).value=p.readout[k];for(const k of this.fields)if(k!=="repetitions")this.$(k).value=p[k];this.$("initial").value=name==="dark"?"fock":"coherent";this.$("echo").value="false";this.$("error").value=name==="biased"?20:0;if(name==="biased")this.$("bias_hz").value=8;this.message("Example staged. Click Run precision benchmark.");}
  buttons(){for(const id of [...this.baseFields,...this.readoutFields,...this.fields,"initial","echo","error","calibrated","biased","dark","run"])this.$(id).disabled=this.running;this.$("pause").disabled=!this.running;this.$("pause").textContent=this.paused?"Resume benchmark":"Pause benchmark";this.$("cancel").disabled=!this.running;for(const id of ["json","csv"])this.$(id).disabled=this.running||!this.data?.records.length||this.data.status==="failed";}
  async run(){let p;try{const v={};for(const k of [...this.baseFields,...this.readoutFields,...this.fields,"error"]){if(!this.$(k).value.trim())throw new Error("Complete all precision settings.");v[k]=Number(this.$(k).value);}p=Precision.validate({...Object.fromEntries(this.fields.map(k=>[k,v[k]])),readout:{...Precision.defaults.readout,...Object.fromEntries(this.readoutFields.map(k=>[k,v[k]])),echo:this.$("echo").value==="true",duration_error:v.error/100,base:{...Precision.defaults.readout.base,...Object.fromEntries(this.baseFields.map(k=>[k,v[k]])),initial:this.$("initial").value}}});}catch(e){this.message(e.message,true);return;}
    this.running=true;this.paused=false;this.cancelled=false;this.data=null;this.$("results").hidden=true;this.buttons();const breathe=()=>new Promise(r=>setTimeout(r,15));
    try{const models=[];for(const item of Precision.configs(p)){this.message(`Preparing ${this.names[item.name].toLowerCase()} output states…`);await breathe();models.push(Precision.modelCase(item));}const records=[];for(let i=0;i<p.repetitions;i++){while(this.paused&&!this.cancelled)await breathe();if(this.cancelled)break;records.push(Precision.trial(p,models,i));this.data=Precision.report(p,models,records,"running");this.message(`${records.length}/${p.repetitions} full-scan repetitions completed in all three cases.`);if(records.length===1||records.length%5===0)this.render();await breathe();}this.data=Precision.report(p,models,records,records.length===p.repetitions?"complete":"cancelled");this.message(`${this.data.status==="complete"?"Complete":"Cancelled"} · ${records.length}/${p.repetitions} paired repetitions · ${(records.length*Precision.drawsPerTrial(p)).toLocaleString()} fresh count outcomes.`);}catch(e){if(this.data)this.data.status="failed";this.message(`Stopped: ${e.message}`,true);}finally{this.running=false;this.paused=false;this.buttons();this.render();}}
  download(ext,text){const url=URL.createObjectURL(new Blob([text],{type:ext==="json"?"application/json":"text/csv"})),a=document.createElement("a");a.href=url;a.download=`coldatomlab-precision.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  render(){const d=this.data;if(!d?.records.length)return;this.$("results").hidden=false;const fmt=x=>x===null?"Unavailable":x.toFixed(4),p=d.plan.readout;
    this.$("applied").textContent=`Displayed: ${d.records.length}/${d.plan.repetitions} paired full scans · ${p.points} settings each · initial ${p.base.initial}, phase=${p.base.phase} rad, left fraction=${p.base.left_fraction}, σ=${p.base.sigma} atoms · hold=${p.hold_ms} ms${p.echo?' with ideal echo':''} · U=${p.base.interaction_hz} Hz, δ=${p.base.bias_hz} Hz · J=${p.pulse_j_hz} Hz · duration error=${p.duration_error*100}% · seed ${p.seed}.`;
    this.$("budgets").innerHTML=d.models.map(m=>{const p=m.plan,clouds=p.points*p.shots;return `<tr><td>${this.names[m.name]}</td><td>${p.base.atoms}</td><td>${p.shots}</td><td>${clouds}</td><td>${clouds*p.base.atoms}</td><td>${fmt(m.ideal_scatter_guide)}</td></tr>`;}).join('');
    this.$("summary").innerHTML=d.models.flatMap(m=>Precision.arms.map(a=>{const s=d.summary[m.name][a];return `<tr><td>${this.names[m.name]} / ${a}</td><td>${s.resolved} / ${s.attempted}</td><td>${fmt(s.circular_bias)}</td><td>${fmt(s.circular_scatter)}</td><td>${fmt(s.rms_reported_se)}</td><td>${fmt(s.scatter_over_se)}</td><td>${fmt(s.wrapped_rmse)}</td><td>${s.within_one_se===null?'Unavailable':(100*s.within_one_se).toFixed(1)+'%'}</td><td>${fmt(s.model_bias)}</td></tr>`;})).join('');
    const w=Math.max(230,this.$("scaling").clientWidth),L=48,R=w-18,T=22,B=185,max=1.15*Math.max(.001,...d.models.flatMap(m=>[m.ideal_scatter_guide??0,...Precision.arms.flatMap(a=>{const s=d.summary[m.name][a];return [s.circular_scatter??0,s.rms_reported_se??0];})])),Y=v=>B-v/max*(B-T),X=i=>L+(i+.5)/3*(R-L);
    let svg=`<svg viewBox="0 0 ${w} 233" role="img" aria-label="Precision versus atoms and shots">`;
    for(let k=0;k<=3;k++){const v=k*max/3;svg+=`<path d="M${L} ${Y(v)}H${R}" stroke="#e0e7e4"/><text x="${L-5}" y="${Y(v)+4}" text-anchor="end">${v.toFixed(3)}</text>`;}
    d.models.forEach((m,i)=>{svg+=`<text x="${X(i)}" y="210" text-anchor="middle">${w<400?["Base","N ↑","Shots ↑"][i]:this.names[m.name]}</text>`;Precision.arms.forEach((a,j)=>{const s=d.summary[m.name][a],x=X(i)+(j-.5)*16,col=this.colors[a];if(s.circular_scatter!==null)svg+=`<circle cx="${x}" cy="${Y(s.circular_scatter)}" r="4" fill="${col}"/>`;if(s.rms_reported_se!==null)svg+=`<rect x="${x-4}" y="${Y(s.rms_reported_se)-4}" width="8" height="8" fill="none" stroke="${col}"/>`;});if(m.ideal_scatter_guide!==null){const x=X(i),y=Y(m.ideal_scatter_guide);svg+=`<path d="M${x-4} ${y-4}L${x+4} ${y+4}M${x-4} ${y+4}L${x+4} ${y-4}" stroke="#283f37"/>`;}});
    svg+=`<text x="${L}" y="14">Phase scatter / rad</text></svg>`;this.$("scaling").innerHTML=svg;
    const name=this.$("case").value,m=d.models.find(m=>m.name===name),truth=m.source.phase;
    if(truth===null){this.$("histogram").innerHTML="";this.$("hist-note").textContent="No identifiable incoming model phase. Error histograms, bias and RMSE are unavailable; inspect the resolved counts above.";return;}
    const errors=Object.fromEntries(Precision.arms.map(a=>[a,d.records.map(r=>r.cases[name][a].fit.phase).filter(x=>x!==null).map(x=>Precision.wrap(x-truth))])),all=Object.values(errors).flat(),lo0=Math.min(0,...all),hi0=Math.max(0,...all),pad=Math.max(.005,(hi0-lo0)*.08),lo=Math.max(-Math.PI,lo0-pad),hi=Math.min(Math.PI,hi0+pad),bins=32,binWidth=(hi-lo)/bins;
    const counts=Object.fromEntries(Precision.arms.map(a=>{const h=Array(bins).fill(0);errors[a].forEach(x=>h[Math.max(0,Math.min(bins-1,Math.floor((x-lo)/binWidth)))]++);return [a,h];})),peak=Math.max(1,...Object.values(counts).flat())/d.records.length*1.15,HX=x=>L+(x-lo)/(hi-lo)*(R-L),HY=y=>B-y/peak*(B-T);
    let hist=`<svg viewBox="0 0 ${w} 241" role="img" aria-label="Distribution of repeated phase errors">`;
    for(let k=0;k<=4;k++){const x=lo+(hi-lo)*k/4;hist+=`<text x="${HX(x)}" y="208" text-anchor="middle">${x.toFixed(3)}</text>`;}
    for(let k=0;k<=3;k++){const y=peak*k/3;hist+=`<path d="M${L} ${HY(y)}H${R}" stroke="#e0e7e4"/><text x="${L-5}" y="${HY(y)+4}" text-anchor="end">${y.toFixed(2)}</text>`;}
    for(const a of Precision.arms){counts[a].forEach((v,k)=>{hist+=`<rect x="${HX(lo+k*binWidth)}" y="${HY(v/d.records.length)}" width="${(R-L)/bins*.9}" height="${B-HY(v/d.records.length)}" fill="${this.colors[a]}" opacity=".65"/>`;});const bias=d.summary[name][a].model_bias;if(bias!==null&&bias>=lo&&bias<=hi)hist+=`<path d="M${HX(bias)} ${T}V${B}" stroke="${this.colors[a]}" stroke-dasharray="3 4"/>`;}
    hist+=`<path d="M${HX(0)} ${T}V${B}" stroke="#283f37"/><text x="${L}" y="14">Fraction of completed scans</text><text x="${w/2}" y="236" text-anchor="middle">Estimated phase − true phase / rad</text></svg>`;this.$("histogram").innerHTML=hist;
    this.$("hist-note").textContent=`${this.names[name]} · true phase=${truth.toFixed(4)} rad · ideal ${errors.ideal.length}/${d.records.length} and finite ${errors.finite.length}/${d.records.length} resolved. Green: ideal mixing. Amber: finite pulse. Each estimate comes from ${m.plan.points*m.plan.shots} newly prepared clouds.`;
  }
};
