"use strict";
globalThis.FinitePulsePanel = class {
  constructor(root){
    this.root=root;this.data=null;this.running=false;this.paused=false;this.cancelled=false;this.timer=null;
    this.names={no_echo:"No pulse",ideal:"Instantaneous swap",short:"Short pulse",nominal:"Nominal π pulse",long:"Long pulse"};
    this.colors={no_echo:"#87948e",ideal:"#283f37",short:"#ba7b2c",nominal:"#16796e",long:"#a84e61"};
    root.innerHTML=`<div class="panel-title"><div><p class="eyebrow">FINITE PULSE / EVOLUTION DURING THE EXCHANGE</p><h2>A pulse takes time.</h2></div><span class="tag">Prescribed two-mode tunnelling</span></div>
      <p>Turn on tunnelling briefly instead of swapping the modes instantly. Bias and interactions keep acting throughout the pulse. All five arms share the same initial state, static offsets and total elapsed time.</p>
      <div class="tm-actions"><button id="fp-echo">Compare echo recovery</button><button id="fp-transfer">Watch population transfer</button><button id="fp-interacting">Keep interactions during pulse</button></div>
      <div class="ep-controls"><label>Atoms N<input id="fp-atoms" type="number" min="2" max="100" step="1" value="40"></label><label>Interaction U / Hz<input id="fp-interaction_hz" type="number" min="0" max="2" step="any" value="0"></label><label>Total elapsed time / ms<input id="fp-duration_ms" type="number" min="1" max="1000" step="any" value="500"></label><label>Pulse J / Hz<input id="fp-pulse_j_hz" type="number" min="0.5" max="20" step="any" value="10"></label><label>Duration error ± / %<input id="fp-error" type="number" min="0" max="50" step="any" value="20"></label><label>Preparations<input id="fp-preparations" type="number" min="2" max="128" step="1" value="32"></label><label>Seed<input id="fp-seed" type="number" min="0" max="4294967295" step="1" value="17"></label></div>
      <details><summary>Initial state and static offsets</summary><div class="ep-controls"><label>Initial left fraction<input id="fp-left_fraction" type="number" min="0" max="1" step="any" value="0.5"></label><label>Initial phase / rad<input id="fp-phase" type="number" min="-3.141592653589793" max="3.141592653589793" step="any" value="0"></label><label>Base bias / Hz<input id="fp-bias_hz" type="number" min="-20" max="20" step="any" value="0"></label><label>Phase variation ± / rad<input id="fp-phase_half_range" type="number" min="0" max="3.141592653589793" step="any" value="0"></label><label>Bias variation ± / Hz<input id="fp-bias_half_range_hz" type="number" min="0" max="5" step="any" value="2"></label></div></details>
      <p class="muted">Coherent initial state. Uniform independent phase and bias offsets; each bias stays fixed. J = 0 outside each pulse. Settings apply on Run finite-pulse comparison.</p>
      <div class="tm-actions"><button id="fp-run" class="primary">Run finite-pulse comparison</button><button id="fp-pause" disabled>Pause computation</button><button id="fp-cancel" disabled>Cancel comparison</button><button id="fp-json" disabled>Export pulse JSON</button><button id="fp-csv" disabled>Export pulse CSV</button></div>
      <p id="fp-status" role="status" aria-live="polite">Ready. Earlier experiments and their results are preserved.</p>
      <div id="fp-results" hidden><p id="fp-applied" class="muted"></p><p id="fp-calibration" class="se-explanation"></p>
      <div class="ep-table fp-summary"><table><thead><tr><th>Arm</th><th>Pulse width / ms</th><th>Final ensemble C</th><th>Final mean left fraction</th><th>Mean fidelity to ideal</th></tr></thead><tbody id="fp-summary"></tbody></table></div>
      <p class="muted">Fidelity compares each complete final many-body state to its paired ideal-swap state, then averages those overlaps. It ignores global phase and is not an experimental gate calibration.</p>
      <div class="ep-controls"><label>Inspect finite arm<select id="fp-arm"><option value="nominal">Nominal π pulse</option><option value="short">Short pulse</option><option value="long">Long pulse</option></select></label><label>Inspect preparation<input id="fp-member" type="number" min="1" step="1" value="1"></label></div>
      <div class="se-sequence"><div id="fp-stage-first"><span>01 / FIRST HOLD</span><b>J = 0</b></div><div id="fp-stage-pulse"><span>02 / RECTANGULAR PULSE</span><b id="fp-pulse-label"></b></div><div id="fp-stage-second"><span>03 / SECOND HOLD</span><b>J = 0</b></div></div>
      <div class="se-scrub"><div><h3 id="fp-time"></h3><p id="fp-stage-note" class="muted"></p></div><button id="fp-play">Play pulse timeline</button></div><label class="se-slider">Inspect time<input id="fp-slider" type="range" min="0" step="1" value="0"></label>
      <div class="tm-actions"><button id="fp-start">Start</button><button id="fp-on">Pulse starts</button><button id="fp-middle">Pulse midpoint</button><button id="fp-off">Pulse ends</button><button id="fp-end">End</button></div>
      <p class="muted">The time axis includes every pulse boundary. Consecutive boundary snapshots preserve the state across finite switching, while the Hamiltonian can change. Playback selects computed states; it does not set the physical time step.</p>
      <div class="se-vector-grid"><section class="tm-panel"><h3>Population transfer</h3><label class="fp-zoom"><input id="fp-zoom" type="checkbox" checked>Zoom around the pulse</label><div id="fp-population" class="chart"></div><div id="fp-population-legend" class="fp-legend"></div><p class="muted">Left fraction in the selected preparation, for all five arms. The shaded interval is the selected finite pulse.</p></section><section class="tm-panel"><h3>Phase during the pulse</h3><div id="fp-vectors" class="chart"></div><p id="fp-selected"></p><p class="muted">Each arrow is one arm's q = 2⟨a†L aR⟩/N for the selected preparation. Length is first-order coherence; phase is unavailable at C ≤ 10⁻⁸. Population can change even when the initial vector has zero length.</p></section></div>
      <section class="tm-panel se-history-panel"><h3>Ensemble coherence</h3><div id="fp-coherence" class="chart"></div><div id="fp-legend" class="fp-legend"></div><p class="muted">Magnitude of the complex average across preparations. A high coherence alone does not prove that the pulse exchanged the modes correctly; also inspect population transfer and fidelity.</p></section>
      <p id="fp-explanation" class="se-explanation"></p></div>
      <details><summary>Pulse calibration, units and limits</summary><p>H/h = −J(a†L aR + a†R aL) + U(n−N/2)² − δ(n−N/2). J, U and δ are in Hz; displayed times are ms. U uses the on-site pair convention, and Σ|cₙ|² = 1. No real-time renormalization is applied.</p><p>With U = δ = 0, a resonant π exchange takes τπ = 1/(4J) seconds. Short and long pulses use (1−error)τπ and (1+error)τπ. The nominal width is a zero-detuning calibration; it is not guaranteed to be a perfect π pulse with bias or interactions. Each finite pulse is centered on T/2 and replaces part of the free hold, so all arms have the same total T.</p><p>The spectral solver propagates the incoming complex state through the driven Hamiltonian. Bias and U are never switched off to make the exchange perfect. The finite π operation is iᴺ times the ideal swap in the resonant limit; this global phase is retained in exported amplitudes and ignored only when evaluating fidelity.</p><p>These are fixed spatial modes with a prescribed rectangular J(t), not a computed barrier ramp, electromagnetic drive, or a simulation of higher orbital excitations. Fast switching can invalidate the two-mode approximation in a real trap. Pulse edges can change energy; no drive-energy budget is modeled. Within each fixed segment, norm and energy are conserved. Time-varying noise, losses and detector effects are omitted.</p><p><a href="https://arxiv.org/html/1203.5359v1" target="_blank" rel="noopener">Gross (2012) ↗</a> provides the coupled two-mode/spin framework; <a href="https://journals.aps.org/pr/abstract/10.1103/PhysRev.80.580" target="_blank" rel="noopener">Hahn (1950) ↗</a> supplies echo context. Pulse calibration here is derived from our stated Hamiltonian, not fitted to those experiments.</p></details>`;
    this.$=id=>root.querySelector(`#fp-${id}`);
    this.baseFields=["atoms","interaction_hz","duration_ms","left_fraction","phase","bias_hz"];
    this.planFields=["pulse_j_hz","phase_half_range","bias_half_range_hz","preparations","seed"];
    for(const name of ["echo","transfer","interacting"])this.$(name).onclick=()=>this.preset(name);
    this.$("run").onclick=()=>this.run();
    this.$("pause").onclick=()=>{this.paused=!this.paused;this.buttons();this.message(this.paused?"Paused between completed preparations.":"Resuming comparison…");};
    this.$("cancel").onclick=()=>{this.cancelled=true;this.paused=false;};
    for(const id of ["slider","arm","member","zoom"])this.$(id).oninput=()=>{this.stop();this.render();};
    for(const name of ["start","on","middle","off","end"])this.$(name).onclick=()=>this.jump(name);
    this.$("play").onclick=()=>{if(this.timer){this.stop();return;}if(+this.$("slider").value===+this.$("slider").max)this.$("slider").value=0;this.$("play").textContent="Pause pulse timeline";this.render();this.timer=setInterval(()=>{this.$("slider").value=+this.$("slider").value+1;this.render();if(+this.$("slider").value===+this.$("slider").max)this.stop();},80);};
    this.$("json").onclick=()=>this.download("coldatomlab-pulse.json",JSON.stringify(this.data,null,2),"application/json");
    this.$("csv").onclick=()=>{const d=this.data,keys=Object.keys(d.aggregate.ideal.history[0]),baseKeys=Object.keys(d.plan.base);const rows=[["arm","status","completed","requested","seed","pulse_j_hz","duration_error","phase_half_range","bias_half_range_hz",...baseKeys,"side",...keys].join(",")];for(const arm of FinitePulse.arms)d.aggregate[arm].history.forEach((r,i)=>rows.push([arm,d.status,d.records.length,d.plan.preparations,d.plan.seed,d.plan.pulse_j_hz,d.plan.duration_error,d.plan.phase_half_range,d.plan.bias_half_range_hz,...baseKeys.map(k=>d.plan.base[k]),d.checkpoints[i].side,...keys.map(k=>r[k])].join(",")));this.download("coldatomlab-pulse.csv",rows.join("\n")+"\n","text/csv");};
    new ResizeObserver(()=>this.render()).observe(this.$("coherence"));
  }
  preset(name){const p=FinitePulse.defaults;const base={...p.base,...(name==="transfer"?{left_fraction:1,duration_ms:100}:name==="interacting"?{interaction_hz:.3,duration_ms:250}:{})};for(const k of this.baseFields)this.$(k).value=base[k];for(const k of this.planFields)if(!["preparations","seed"].includes(k))this.$(k).value=k==="bias_half_range_hz"&&name==="transfer"?0:p[k];this.$("error").value=20;this.message("Example staged. Click Run finite-pulse comparison.");}
  message(text,error=false){this.$("status").textContent=text;this.$("status").classList.toggle("error",error);}
  stop(){clearInterval(this.timer);this.timer=null;this.$("play").textContent="Play pulse timeline";}
  buttons(){for(const id of [...this.baseFields,...this.planFields,"error","echo","transfer","interacting","run"])this.$(id).disabled=this.running;this.$("pause").disabled=!this.running;this.$("pause").textContent=this.paused?"Resume computation":"Pause computation";this.$("cancel").disabled=!this.running;for(const id of ["json","csv"])this.$(id).disabled=this.running||!this.data?.records.length||this.data.status==="failed";for(const id of ["slider","play","arm","member","start","on","middle","off","end"])this.$(id).disabled=this.running;}
  async run(){let p;try{const v={};for(const k of [...this.baseFields,...this.planFields,"error"]){if(!this.$(k).value.trim())throw new Error("Complete all finite-pulse settings.");v[k]=Number(this.$(k).value);}p=FinitePulse.validate({...Object.fromEntries(this.planFields.map(k=>[k,v[k]])),duration_error:v.error/100,base:{...FinitePulse.defaults.base,...Object.fromEntries(this.baseFields.map(k=>[k,v[k]]))}});}catch(e){this.message(e.message,true);return;}
    this.stop();this.data=null;this.$("results").hidden=true;this.running=true;this.paused=false;this.cancelled=false;this.buttons();this.message("Preparing the five-arm reference…");const breathe=()=>new Promise(resolve=>setTimeout(resolve,20));
    try{await breathe();const ref=FinitePulse.reference(p),records=[];this.data=FinitePulse.report(p,ref,records,"running");this.$("slider").max=this.data.checkpoints.length-1;this.$("slider").value=this.$("slider").max;this.$("member").value=1;
      for(const recipe of Preparation.recipes(FinitePulse.ensemble(p))){while(this.paused&&!this.cancelled)await breathe();if(this.cancelled)break;records.push(FinitePulse.evolve(p,recipe));this.data=FinitePulse.report(p,ref,records,"running");this.$("member").max=records.length;this.message(`${records.length}/${p.preparations} five-arm preparations completed.`);if(records.length===1||records.length%4===0)this.render();await breathe();}
      this.data=FinitePulse.report(p,ref,records,records.length===p.preparations?"complete":"cancelled");this.message(`${this.data.status==="complete"?"Complete":"Cancelled"} · ${records.length}/${p.preparations} preparations retained in all five arms.`);
    }catch(e){if(this.data)this.data.status="failed";this.message(`Stopped: ${e.message}`,true);}finally{this.running=false;this.paused=false;this.buttons();this.render();}}
  download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  jump(name){if(!this.data?.records.length)return;this.stop();const d=this.data,w=d.windows[this.$("arm").value],t={start:0,on:w.start_ms,middle:d.plan.base.duration_ms/2,off:w.end_ms,end:d.plan.base.duration_ms}[name];const i=d.checkpoints.findIndex(x=>Math.abs(x.time_ms-t)<1e-9&&x.side==="after");this.$("slider").value=i;this.render();}
  chart(id,key,member,i){const d=this.data,T=d.plan.base.duration_ms,w=Math.max(210,this.$(id).clientWidth),left=38,right=w-12,top=22,bottom=201,win=d.windows[this.$("arm").value],zoom=id==="population"&&this.$("zoom").checked,lo=zoom?Math.max(0,d.windows.long.start_ms-d.windows.long.width_ms*.2):0,hi=zoom?Math.min(T,d.windows.long.end_ms+d.windows.long.width_ms*.2):T,X=t=>left+(t-lo)/(hi-lo)*(right-left),Y=x=>bottom-x*(bottom-top);let svg=`<svg viewBox="0 0 ${w} 242" role="img" aria-label="${key} versus physical time"><rect x="${X(win.start_ms)}" y="${top}" width="${X(win.end_ms)-X(win.start_ms)}" height="${bottom-top}" fill="#edf3ef"/><defs><clipPath id="fp-clip-${id}"><rect x="${left}" y="${top-2}" width="${right-left}" height="${bottom-top+4}"/></clipPath></defs>`;
    for(let k=0;k<=4;k++)svg+=`<path d="M${left} ${Y(k/4)}H${right}" stroke="#e0e7e4"/><text x="${left-5}" y="${Y(k/4)+4}" text-anchor="end">${k/4}</text><text x="${X(lo+(hi-lo)*k/4)}" y="223" text-anchor="middle">${Number((lo+(hi-lo)*k/4).toFixed(2))}</text>`;
    for(const arm of FinitePulse.arms){const rows=member===null?d.aggregate[arm].history:d.records[member].arms[arm].history;svg+=`<path d="${rows.map((r,k)=>`${k?'L':'M'}${X(r.time_ms)} ${Y(key==="Left fraction"?r.mean_left/d.plan.base.atoms:r.ensemble_coherence)}`).join(' ')}" clip-path="url(#fp-clip-${id})" fill="none" stroke="${this.colors[arm]}" stroke-width="${arm===this.$("arm").value?2.5:1.5}" stroke-dasharray="${arm==='ideal'?'5 4':arm==='no_echo'?'2 4':''}"/>`;}
    svg+=`<path d="M${X(d.checkpoints[i].time_ms)} ${top}V${bottom}" stroke="#344a40" clip-path="url(#fp-clip-${id})"/><text x="${left}" y="14">${key}</text><text x="${w/2}" y="239" text-anchor="middle">Time / ms</text></svg>`;this.$(id).innerHTML=svg;}
  render(){const d=this.data;if(!d?.records.length)return;this.$("results").hidden=false;const arm=this.$("arm").value,i=+this.$("slider").value,member=Math.max(0,Math.min(d.records.length-1,(parseInt(this.$("member").value,10)||1)-1)),record=d.records[member],r=record.arms[arm].history[i],point=d.checkpoints[i],win=d.windows[arm],N=d.plan.base.atoms;
    this.$("applied").textContent=`Displayed: ${d.records.length}/${d.plan.preparations} preparations · N=${N}, U=${d.plan.base.interaction_hz} Hz, total T=${d.plan.base.duration_ms} ms · Jpulse=${d.plan.pulse_j_hz} Hz · duration error ±${d.plan.duration_error*100}% · seed ${d.plan.seed} · initial left fraction=${d.plan.base.left_fraction}, phase=${d.plan.base.phase} rad, base bias=${d.plan.base.bias_hz} Hz · phase spread ±${d.plan.phase_half_range.toFixed(3)} rad, bias spread ±${d.plan.bias_half_range_hz} Hz.`;
    this.$("calibration").textContent=`Nominal resonant π width: ${Number(d.windows.nominal.width_ms.toFixed(4))} ms. Short: ${Number(d.windows.short.width_ms.toFixed(4))} ms. Long: ${Number(d.windows.long.width_ms.toFixed(4))} ms. Every pulse is centered at ${d.plan.base.duration_ms/2} ms; the holds fill the remaining time.`;
    this.$("summary").innerHTML=FinitePulse.arms.map(a=>{const v=d.aggregate[a],end=v.history.at(-1);return `<tr><td style="color:${this.colors[a]}">${this.names[a]}</td><td>${d.windows[a]?d.windows[a].width_ms.toFixed(4):a==='ideal'?'0 (ideal)':'—'}</td><td>${end.ensemble_coherence.toFixed(4)}</td><td>${(end.mean_left/N).toFixed(4)}</td><td>${v.mean_fidelity_to_ideal.toFixed(4)}</td></tr>`;}).join("");
    const boundary=d.checkpoints.some((x,k)=>k!==i&&Math.abs(x.time_ms-point.time_ms)<1e-9);this.$("time").textContent=`t = ${Number(point.time_ms.toFixed(4))} ms${boundary?` · ${point.side} boundary`:""}`;
    this.$("stage-note").textContent=`${this.names[arm]}: ${['first hold','pulse active','second hold'][r.stage]} · applied J = ${r.active_j_hz} Hz · pulse ${Number(win.start_ms.toFixed(4))}–${Number(win.end_ms.toFixed(4))} ms.`;
    this.$("pulse-label").textContent=`J = ${d.plan.pulse_j_hz} Hz`;["first","pulse","second"].forEach((name,k)=>this.$(`stage-${name}`).classList.toggle("active",r.stage===k));
    this.chart("population","Left fraction",member,i);this.chart("coherence","Ensemble C",null,i);
    const w=Math.max(210,this.$("vectors").clientWidth),cx=w/2,cy=105,radius=Math.min(78,(w-65)/2);let svg=`<svg viewBox="0 0 ${w} 230" role="img" aria-label="Coherence vectors of selected preparation"><circle cx="${cx}" cy="${cy}" r="${radius}" fill="none" stroke="#c8d4cf"/><path d="M${cx-radius} ${cy}H${cx+radius}M${cx} ${cy-radius}V${cy+radius}" stroke="#e0e7e4"/><text x="${cx+radius+4}" y="${cy+4}">Re</text><text x="${cx+4}" y="${cy-radius-5}">Im</text>`;
    for(const a of FinitePulse.arms){const s=record.arms[a].history[i],x=cx+radius*s.coherence_real,y=cy-radius*s.coherence_imag;svg+=`<defs><marker id="fp-arrow-${a}" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="4" markerHeight="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="${this.colors[a]}"/></marker></defs><path d="M${cx} ${cy}L${x} ${y}" stroke="${this.colors[a]}" stroke-width="${a===arm?3:1.5}" ${s.coherence>1e-8?`marker-end="url(#fp-arrow-${a})"`:''}/>`;}
    svg+=`<text x="${cx}" y="220" text-anchor="middle">Preparation ${member+1} · selected C = ${r.coherence.toFixed(4)}</text></svg>`;this.$("vectors").innerHTML=svg;
    this.$("selected").textContent=`${this.names[arm]}: ⟨NL⟩=${r.mean_left.toFixed(3)}, ⟨NR⟩=${(N*r.norm-r.mean_left).toFixed(3)} · phase ${r.coherence>1e-8?Math.atan2(r.coherence_imag,r.coherence_real).toFixed(3)+' rad':'Unavailable'}. Static bias=${record.config.bias_hz.toFixed(4)} Hz; initial phase=${record.config.phase.toFixed(4)} rad.`;
    this.$("population-legend").innerHTML=this.$("legend").innerHTML=FinitePulse.arms.map(a=>`<span style="color:${this.colors[a]}">━ ${this.names[a]}</span>`).join("");
    this.$("explanation").textContent=`The nominal π width is calibrated at U = δ = 0. Here U=${d.plan.base.interaction_hz} Hz and each preparation keeps its own bias during the pulse. Short/long pulses change duration, not total elapsed time. Values are computed from full occupation amplitudes; no perfect swap is inserted into a finite arm.`;
  }
};
