"use strict";
globalThis.ReadoutPanel=class {
  constructor(root){
    this.root=root;this.data=null;this.running=false;this.cancelled=false;this.paused=false;
    this.names={direct:"Direct counting",ideal:"Ideal π/2 mixing",finite:"Finite π/2 pulse"};
    this.colors={direct:"#87948e",ideal:"#16796e",finite:"#ba7b2c"};
    root.innerHTML=`<div class="panel-title"><div><p class="eyebrow">PHASE READOUT / MEASURE IN A DIFFERENT BASIS</p><h2>Read phase through atom counts.</h2></div><span class="tag">Independent preparations · ideal counting</span></div>
    <p>Direct counting measures populations. A final mixing pulse converts coherence into a population difference. Scan a controlled reference phase, repeat the preparation at every shot, then infer phase from the counts.</p>
    <div class="tm-actions"><button id="rd-coherent">Read a coherent phase</button><button id="rd-detuned">Try a biased pulse</button><button id="rd-fock">Try a fixed-number state</button></div>
    <div class="ep-controls"><label>Atoms N<input id="rd-atoms" type="number" min="2" max="100" value="40"></label><label>Initial phase / rad<input id="rd-phase" type="number" step="any" value="0.7"></label><label>Hold / ms<input id="rd-hold_ms" type="number" min="0" max="1000" step="any" value="0"></label><label>Interaction U / Hz<input id="rd-interaction_hz" type="number" min="0" max="2" step="any" value="0"></label><label>Bias δ / Hz<input id="rd-bias_hz" type="number" min="-20" max="20" step="any" value="0"></label><label>Readout J / Hz<input id="rd-pulse_j_hz" type="number" min="0.5" max="20" step="any" value="10"></label><label>Pulse duration error / %<input id="rd-error" type="number" min="-50" max="50" step="any" value="0"></label><label>Shots per setting / arm<input id="rd-shots" type="number" min="16" max="4096" value="256"></label><label>Reference phase settings<input id="rd-points" type="number" min="8" max="32" value="12"></label><label>Seed<input id="rd-seed" type="number" min="0" max="4294967295" value="17"></label></div>
    <details><summary>Preparation and echo</summary><div class="ep-controls"><label>Initial state<select id="rd-initial"><option value="coherent">Coherent binomial</option><option value="gaussian">Prescribed number-narrow state</option><option value="fock">Fixed occupation</option></select></label><label>Initial left fraction<input id="rd-left_fraction" type="number" min="0" max="1" step="any" value="0.5"></label><label>Gaussian σ / atoms<input id="rd-sigma" type="number" min="0.25" max="20" step="any" value="1.5"></label><label>During the hold<select id="rd-echo"><option value="false">Free isolated hold</option><option value="true">Ideal midpoint echo</option></select></label></div><p>J = 0 during the hold. The optional echo is an instantaneous mode swap. Every shot starts from the same prescribed quantum state; there is no technical preparation variation.</p></details>
    <div class="se-sequence"><div><span>01 / PREPARE & EVOLVE</span><b>Hold / optional echo</b></div><div><span>02 / CHOOSE THE BASIS</span><b>Reference phase α → mix</b></div><div><span>03 / COUNT & REPEAT</span><b>Nₗ + Nᵣ = N each shot</b></div></div>
    <div class="tm-actions"><button id="rd-run" class="primary">Run phase readout</button><button id="rd-pause" disabled>Pause scan</button><button id="rd-cancel" disabled>Cancel scan</button><button id="rd-json" disabled>Export readout JSON</button><button id="rd-csv" disabled>Export readout CSV</button></div>
    <p id="rd-status" role="status" aria-live="polite">Ready. Settings apply on Run phase readout; earlier results are preserved.</p>
    <div id="rd-results" hidden><p id="rd-applied" class="muted"></p><p id="rd-truth" class="se-explanation"></p>
    <div id="rd-fringe" class="chart"></div><div id="rd-legend" class="fp-legend"></div><p class="muted">Solid curves: exact model count means. Dots: sampled count means ± one empirical standard error (SEM), not shot-to-shot scatter. Each setting and arm uses fresh independent shots. Dashed curves: first-harmonic fits to those counts.</p>
    <div class="ep-table"><table><thead><tr><th>Readout</th><th>Count-inferred phase / rad</th><th>Local phase SE / rad</th><th>Fitted contrast</th><th>Fit residual RMS / z</th><th>Model readout bias / rad</th></tr></thead><tbody id="rd-fit"></tbody></table></div>
    <p id="rd-fit-note" class="muted"></p>
    <div class="ep-controls"><label>Inspect reference phase<select id="rd-point"></select></label><label>Inspect count distribution<select id="rd-arm"><option value="ideal">Ideal π/2 mixing</option><option value="finite">Finite π/2 pulse</option><option value="direct">Direct counting</option></select></label></div>
    <div id="rd-histogram" class="chart"></div><p id="rd-count-note"></p>
    <p class="muted">Histogram bars are actual simulated count outcomes; the line is P(Nₗ) from the output quantum state. A narrow histogram at one setting alone does not establish improved phase sensitivity.</p></div>
    <details><summary>Conventions, statistics and model limits</summary><p>Fixed spatial modes, basis |n,N−n⟩, Σ|cₙ|² = 1. H/h = −J(a†L aR + a†R aL) + U(n−N/2)² − δ(n−N/2). J, U and δ are in Hz; U is the on-site pair coefficient. Time is displayed in ms. Propagation does not renormalize the state.</p><p>For reference phase α, the ideal phase gate multiplies cₙ by exp[−i(N−n)(α+π/2)]. Positive-J π/2 mixing then gives z = 2⟨Nₗ⟩/N−1 = Re(q exp[−iα]), with q = 2⟨a†L aR⟩/N. At α = 0 and π/2 the ideal readout measures Re(q) and Im(q). The reference-phase gate is prescribed, not a simulated bias pulse.</p><p>The finite pulse lasts (1+error)/(8J) seconds. Bias and interactions remain active throughout it. Ideal mixing is instantaneous; the finite arm adds its displayed pulse duration after the same prepared state. This compares readout operations, not experiments with equal total duration.</p><p>A full-period unweighted harmonic fit uses z = offset + a cos α + b sin α. Phase = atan2(b,a), contrast = hypot(a,b). Covariance comes from empirical count variances divided by shots. The local delta-method phase SE is approximate at high signal-to-noise, not a confidence interval or a quantum precision bound. Phase is unavailable unless contrast exceeds 3 times the largest quadrature standard error (and 10⁻⁸). Contrast is not clipped to 1. Finite-pulse distortions can bias the apparent fringe phase or add higher harmonics; inspect residuals and model-only bias. Statistical SE excludes that systematic error.</p><p>Model truth is diagnostic only and is never fed into the count estimator. Direct counting is not used to infer phase. Partial scans are retained without fitted phase. All measurements are ideal destructive number counts on independently prepared copies. Detector noise, atom loss, time-varying noise, higher spatial modes and apparatus calibration are omitted.</p><p><a href="https://arxiv.org/html/1203.5359v1#S4.SS1" target="_blank" rel="noopener">Gross (2012), section IV.1 ↗</a> describes Ramsey readout using number differences. Here the modes are spatial; this is a teaching model, not a reconstruction of an internal-state microwave experiment.</p></details>`;
    this.$=id=>root.querySelector(`#rd-${id}`);
    this.baseFields=["atoms","phase","interaction_hz","bias_hz","left_fraction","sigma"];
    this.fields=["hold_ms","pulse_j_hz","shots","points","seed"];
    for(const id of ["coherent","detuned","fock"])this.$(id).onclick=()=>this.preset(id);
    this.$("run").onclick=()=>this.run();
    this.$("pause").onclick=()=>{this.paused=!this.paused;this.buttons();this.message(this.paused?"Paused between reference phase settings.":"Resuming scan…");};
    this.$("cancel").onclick=()=>{this.cancelled=true;this.paused=false;};
    for(const id of ["point","arm"])this.$(id).onchange=()=>this.render();
    this.$("json").onclick=()=>this.download("json",JSON.stringify(this.data,null,2));
    this.$("csv").onclick=()=>{const d=this.data,rows=[["status","seed","shots","N","initial","initial_phase_rad","left_fraction","sigma","hold_ms","echo","U_hz","bias_hz","readout_J_hz","duration_error","finite_width_ms","index","alpha_rad","arm","model_mean_left","sample_mean_left","sem_left","phase_rad","phase_se_rad","contrast","residual_rms_z"]];for(const r of d.records)for(const arm of Readout.arms){const a=r.arms[arm],f=d.fits?.[arm]?.measured,p=d.plan,b=p.base;rows.push([d.status,p.seed,p.shots,b.atoms,b.initial,b.phase,b.left_fraction,b.sigma,p.hold_ms,p.echo,b.interaction_hz,b.bias_hz,p.pulse_j_hz,p.duration_error,d.finite_width_ms,r.index,r.alpha,arm,a.state.mean_left,a.statistics.mean_left,a.statistics.sem_left,f?.phase??"",f?.phase_se??"",f?.contrast??"",f?.residual_rms??""]);}this.download("csv",rows.map(r=>r.join(",")).join("\n")+"\n");};
    new ResizeObserver(()=>this.render()).observe(this.$("fringe"));
  }
  message(t,error=false){this.$("status").textContent=t;this.$("status").classList.toggle("error",error);}
  preset(name){const p=Readout.defaults;for(const k of this.baseFields)this.$(k).value=p.base[k];for(const k of this.fields)if(!["seed","shots"].includes(k))this.$(k).value=p[k];this.$("initial").value=name==="fock"?"fock":"coherent";this.$("echo").value="false";this.$("error").value=0;if(name==="detuned"){this.$("bias_hz").value=8;this.$("error").value=20;}this.message("Example staged. Click Run phase readout.");}
  buttons(){for(const id of [...this.baseFields,...this.fields,"initial","echo","error","coherent","detuned","fock","run"])this.$(id).disabled=this.running;this.$("pause").disabled=!this.running;this.$("pause").textContent=this.paused?"Resume scan":"Pause scan";this.$("cancel").disabled=!this.running;for(const id of ["json","csv"])this.$(id).disabled=this.running||!this.data?.records.length||this.data.status==="failed";}
  async run(){let p;try{const v={};for(const k of [...this.baseFields,...this.fields,"error"]){if(!this.$(k).value.trim())throw new Error("Complete all readout settings.");v[k]=Number(this.$(k).value);}p=Readout.validate({...Object.fromEntries(this.fields.map(k=>[k,v[k]])),echo:this.$("echo").value==="true",duration_error:v.error/100,base:{...Readout.defaults.base,...Object.fromEntries(this.baseFields.map(k=>[k,v[k]])),initial:this.$("initial").value}});}catch(e){this.message(e.message,true);return;}
    this.running=true;this.cancelled=false;this.paused=false;this.data=null;this.$("results").hidden=true;this.$("point").innerHTML="";this.buttons();this.message("Preparing the input state…");const breathe=()=>new Promise(r=>setTimeout(r,35));
    try{await breathe();const source=Readout.incoming(p),records=[];for(let i=0;i<p.points;i++){while(this.paused&&!this.cancelled)await breathe();if(this.cancelled)break;records.push(Readout.point(p,source,i));this.data=Readout.report(p,source,records,"running");this.$("point").add(new Option(`${i+1} · α = ${records[i].alpha.toFixed(3)} rad`,i));this.message(`${records.length}/${p.points} reference phase settings completed.`);this.render();await breathe();}this.data=Readout.report(p,source,records,records.length===p.points?"complete":"cancelled");this.message(`${this.data.status==="complete"?"Complete":"Cancelled"} · ${records.length}/${p.points} settings · ${records.length*p.shots*3} independent shots across three arms.`);}catch(e){if(this.data)this.data.status="failed";this.message(`Stopped: ${e.message}`,true);}finally{this.running=false;this.paused=false;this.buttons();this.render();}}
  download(ext,text){const url=URL.createObjectURL(new Blob([text],{type:ext==="json"?"application/json":"text/csv"})),a=document.createElement("a");a.href=url;a.download=`coldatomlab-readout.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  render(){const d=this.data;if(!d?.records.length)return;this.$("results").hidden=false;const p=d.plan,N=p.base.atoms,fmt=x=>x===null?"Unavailable":x.toFixed(4),s=d.source;
    this.$("applied").textContent=`Displayed: N=${N}, ${p.base.initial}, initial phase=${p.base.phase} rad, left fraction=${p.base.left_fraction}, σ=${p.base.sigma} atoms · hold=${p.hold_ms} ms${p.echo?' with ideal midpoint echo':''} · U=${p.base.interaction_hz} Hz, δ=${p.base.bias_hz} Hz · J=${p.pulse_j_hz} Hz · width=${d.finite_width_ms.toFixed(4)} ms (${p.duration_error*100}% error) · ${p.shots} shots per setting/arm · seed ${p.seed}.`;
    this.$("truth").textContent=`Before readout — model truth: phase ${fmt(s.phase)}${s.phase===null?'':' rad'}, C=${s.coherence.toFixed(4)}, ⟨Nₗ⟩=${s.mean_left.toFixed(3)}. These values are not supplied to the count estimator.`;
    const w=Math.max(230,this.$("fringe").clientWidth),left=38,right=w-18,top=24,bottom=245,X=a=>left+a/(2*Math.PI)*(right-left),Y=v=>bottom-(v+1.15)/2.3*(bottom-top);
    let svg=`<svg viewBox="0 0 ${w} 292" role="img" aria-label="Population difference versus reference phase">`;
    for(let k=0;k<=4;k++){const z=-1+k/2;svg+=`<path d="M${left} ${Y(z)}H${right}" stroke="#e0e7e4"/><text x="${left-6}" y="${Y(z)+4}" text-anchor="end">${z}</text><text x="${X(k*Math.PI/2)}" y="269" text-anchor="middle">${['0','π/2','π','3π/2','2π'][k]}</text>`;}
    for(const arm of Readout.arms){const col=this.colors[arm];svg+=`<path d="${d.records.map((r,i)=>`${i?'L':'M'}${X(r.alpha)} ${Y(2*r.arms[arm].state.mean_left/N-1)}`).join(' ')}" fill="none" stroke="${col}"/>`;
      for(const r of d.records){const a=r.arms[arm].statistics,x=X(r.alpha),y=Y(a.z),err=2*a.sem_left/N;svg+=`<path d="M${x} ${Y(a.z-err)}V${Y(a.z+err)}" stroke="${col}"/><circle cx="${x}" cy="${y}" r="3" fill="${col}"/>`;}
      const f=d.fits?.[arm]?.measured;if(f)svg+=`<path d="${Array.from({length:101},(_,i)=>{const a=2*Math.PI*i/100;return `${i?'L':'M'}${X(a)} ${Y(f.offset+f.cosine*Math.cos(a)+f.sine*Math.sin(a))}`;}).join(' ')}" fill="none" stroke="${col}" stroke-dasharray="4 4"/>`;
    }svg+=`<text x="${left}" y="14">z = (⟨Nₗ⟩ − ⟨Nᵣ⟩) / N</text><text x="${w/2}" y="289" text-anchor="middle">Reference phase α / rad</text></svg>`;this.$("fringe").innerHTML=svg;
    this.$("legend").innerHTML=Readout.arms.map(a=>`<span style="color:${this.colors[a]}">━ ${this.names[a]}</span>`).join("");
    this.$("fit").innerHTML=["ideal","finite"].map(a=>{const f=d.fits?.[a],m=f?.measured,bias=f&&s.phase!==null&&f.model.phase!==null?Math.atan2(Math.sin(f.model.phase-s.phase),Math.cos(f.model.phase-s.phase)):null;return `<tr><td>${this.names[a]}</td><td>${m?fmt(m.phase):'Pending full scan'}</td><td>${m?fmt(m.phase_se):'—'}</td><td>${m?fmt(m.contrast):'—'}</td><td>${m?fmt(m.residual_rms):'—'}</td><td>${f?fmt(bias):'—'}</td></tr>`;}).join('');
    this.$("fit-note").textContent=d.fits?"Phase SE describes local counting uncertainty only. Unavailable means the harmonic amplitude is unresolved. Finite-pulse phase is an apparent fringe phase: model bias and higher-harmonic residuals are separate from statistical SE. Model bias compares noiseless readout with the pre-readout phase, wrapped to ±π.":"A complete full-period scan is needed for this estimator. Partial results have no inferred phase.";
    const i=Math.min(d.records.length-1,+this.$("point").value||0),arm=this.$("arm").value,a=d.records[i].arms[arm],h=a.measurement.counts,prob=a.state.probability,max=Math.max(...prob,...h.map(v=>v/p.shots),.01)*1.1,L=38,R=w-18,B=184,T=20,bw=(R-L)/(N+1),HX=n=>L+(n+.5)*bw,HY=v=>B-v/max*(B-T);
    let hist=`<svg viewBox="0 0 ${w} 232" role="img" aria-label="Repeated left atom count distribution">`;
    for(let k=0;k<=3;k++){const v=max*k/3;hist+=`<path d="M${L} ${HY(v)}H${R}" stroke="#e0e7e4"/><text x="${L-5}" y="${HY(v)+4}" text-anchor="end">${v.toFixed(2)}</text>`;}
    h.forEach((v,n)=>{hist+=`<rect x="${HX(n)-bw*.4}" y="${HY(v/p.shots)}" width="${bw*.8}" height="${B-HY(v/p.shots)}" fill="${this.colors[arm]}"/>`;});
    hist+=`<path d="${prob.map((v,n)=>`${n?'L':'M'}${HX(n)} ${HY(v)}`).join(' ')}" fill="none" stroke="#283f37"/>`;
    for(const n of [...new Set([0,Math.round(N/4),Math.round(N/2),Math.round(3*N/4),N])])hist+=`<text x="${HX(n)}" y="208" text-anchor="middle">${n}</text>`;
    hist+=`<text x="${L}" y="13">Probability / relative frequency</text><text x="${w/2}" y="230" text-anchor="middle">Measured left atoms Nₗ</text></svg>`;this.$("histogram").innerHTML=hist;
    this.$("count-note").textContent=`${this.names[arm]} · α=${d.records[i].alpha.toFixed(3)} rad · ${p.shots} shots · sample ⟨Nₗ⟩=${a.statistics.mean_left.toFixed(3)} ± ${a.statistics.sem_left.toFixed(3)} SEM · model ⟨Nₗ⟩=${a.state.mean_left.toFixed(3)}. Every count n corresponds to (Nₗ,Nᵣ)=(n,${N}−n).`;
  }
};
